import "@/style/globals.css";
import type { Metadata } from "next";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import Subnav from "@/layout/Subnav";
import { CartProvider } from "@/modules/auth/cartcontext/components/CartProvider";
import { WishlistProvider } from "@/modules/auth/wishlistprovider/hooks/useWishlistProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <WishlistProvider>
          <CartProvider>
            <Header />
            <Subnav />
            {children}
            <Footer />
          </CartProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}
