import "@/style/globals.css";
import type { Metadata } from "next";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import Subnav from "@/layout/Subnav";
import Providers from "@/providers/Providers";
import { CartProvider } from "@/modules/cartcontext/components/CartProvider";
import { WishlistProvider } from "@/modules/wishlistprovider/hooks/useWishlistProvider";

export const metadata: Metadata = {
  title: "E-commerceuikit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Providers>
          <WishlistProvider>
            <CartProvider>
              <Header />
              <Subnav />
              {children}
              <Footer />
            </CartProvider>
          </WishlistProvider>
        </Providers>
      </body>
    </html>
  );
}
